package com.example.nopshop.model.products


data class Data(
    val AddToCart: AddToCart,
    val AllowAddingOnlyExistingAttributeCombinations: Boolean,
    val AssociatedProducts: List<Any> = emptyList(),
    val AvailableEndDate: Any = Any(),
    val Breadcrumb: Breadcrumb,
    val CompareProductsEnabled: Boolean,
    val CurrentStoreName: String,
    val CustomProperties: CustomPropertiesXXX,
    val DefaultPictureModel: DefaultPictureModel,
    val DefaultPictureZoomEnabled: Boolean,
    val DeliveryDate: Any = Any(),
    val DisplayBackInStockSubscription: Boolean,
    val DisplayDiscontinuedMessage: Boolean,
    val EmailAFriendEnabled: Boolean,
    val FreeShippingNotificationEnabled: Boolean,
    val FullDescription: String,
    val GiftCard: GiftCard,
    val Gtin: Any = Any(),
    val HasSampleDownload: Boolean,
    val Id: Int,
    val InStock: Boolean,
    val IsFreeShipping: Boolean,
    val IsRental: Boolean,
    val IsShipEnabled: Boolean,
    val ManageInventoryMethod: Int,
    val ManufacturerPartNumber: Any = Any(),
    val MetaDescription: String,
    val MetaKeywords: Any,
    val MetaTitle: Any,
    val Name: String,
    val PageShareCode: String,
    val PictureModels: List<PictureModel>,
    val ProductAttributes: List<Any> = emptyList(),
    val ProductEstimateShipping: ProductEstimateShipping,
    val ProductManufacturers: List<Any> = emptyList(),
    val ProductPrice: ProductPrice,
    val ProductReviewOverview: ProductReviewOverview,
    val ProductSpecificationModel: ProductSpecificationModel,
    val ProductTags: List<ProductTag> = emptyList(),
    val ProductType: Int,
    val RentalEndDate: Any = Any(),
    val RentalStartDate: Any = Any(),
    val SeName: String,
    val ShortDescription: String,
    val ShowGtin: Boolean,
    val ShowManufacturerPartNumber: Boolean,
    val ShowSku: Boolean,
    val ShowVendor: Boolean,
    val Sku: String,
    val StockAvailability: String,
    val TierPrices: List<TierPrice> = emptyList(),
    val VendorModel: VendorModel,
    val VideoModels: List<VideoModel> = emptyList(),
    val VisibleIndividually: Boolean
)

